### ISSUE TITLE
Hazy Camera Image

### ISSUE THREAD

**Issue by katiekang1998** [StanfordVL/GibsonEnv#19] opened 2018-07-19 21:56 UTC
I am trying to run Gibson Env in space3 initial position [-0.6897, 9.0862, 1.5] and orientation [0, 0, -1.57], with camera fov 0.66666 and resolution 128. The images I am getting for rgb_filled turn out to be very hazy, and I just get a black screen for rgb_prefilled (see attached images). Is there some way I can fix this?

I also tried it on space7, and the rgb_filled looks good, but the rgb_prefilled image is still just black.

Thanks!
![screenshot from 2018-07-19 14-44-48](https://user-images.githubusercontent.com/16585531/42972289-d213ecd6-8b63-11e8-959f-8ba5e06882a1.png)
![screenshot from 2018-07-19 14-46-48](https://user-images.githubusercontent.com/16585531/42972292-d3f794c6-8b63-11e8-862e-bf7480bcbeaf.png)

**Comment by hzyjerry** [comment] 2018-07-20 07:05
Hi, @katiekang1998 thanks for your interest!

First, the black rgb_prefilled is due to a bug in the original code. It's fixed in [commit](https://github.com/StanfordVL/GibsonEnv/commit/b8efecb912b8bf722088ce93f4ac328f43836c17). You can pull from the master branch. Thanks a lot for pointing it out :)

To answer your question on hazy rgb, I'm not entirely sure about the cause atm, but here are a few things you can try:

1. Ensure your asset is downloaded from `wget https://storage.googleapis.com/gibsonassets/assets_core_v2.tar.gz` and placed correctly at `GibsonEnv/gibson/assets`
2. Rebuild in `GibsonEnv` directory by `./build.sh build_local`
3. Try out different resolutions: `512/256`

I used the following configuration in `GibsonEnv/examples/configs/play/play_drone_camera.yaml`:
~~~~envname: DroneNavigateEnv
model_id: space3
target_orn: [0, 0, 1.57]
target_pos: [-14.3, 45.07, 0.5]
initial_orn: [0, 0, -1.57]
initial_pos: [-0.6897, 9.0862, 1.5]
fov: 0.666
is_discrete: true

use_filler: true
display_ui: true
show_diagnostics: false
ui_num: 3
ui_components: [RGB_FILLED, DEPTH, RGB_PREFILLED]
random:
  random_initial_pose : false
  random_target_pose : false
  random_init_x_range: [-0.1, 0.1]
  random_init_y_range: [-0.1, 0.1]
  random_init_z_range: [-0.1, 0.1]
  random_init_rot_range: [-0.1, 0.1]

output: [nonviz_sensor, rgb_filled, depth, rgb_prefilled]
resolution: 128

speed:
  timestep: 0.01
  frameskip: 1

mode: gui #gui|headless
verbose: false
~~~~

I get the following rendering by `python examples/demo/play_drone_camera.py`:

![screenshot from 2018-07-19 23-49-23](https://user-images.githubusercontent.com/7868138/42988124-53542396-8bb0-11e8-8d9e-110bf6c322cf.png)

**Closed** 2018-07-25 22:09 UTC
